version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dzencode_test_task
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: node-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
